/*
 * Copyright 2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dpstudio.module.wxminiprogram.annotation;


import com.dpstudio.module.wxminiprogram.IWxMimiProgramHandler;
import com.dpstudio.module.wxminiprogram.impl.DefaultWxMimiProgramHandler;

import java.lang.annotation.*;

/**
 * SecurityConf generated By ModuleMojo on 2020/06/30 17:49
 *
 * @author YMP (https://www.ymate.net/)
 */
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface WxMiniProgramConf {

    /**
     * @return 模块是否已启用, 默认值: true
     */
    boolean enabled() default true;

    /**
     * @return appId
     */
    String appId() default "";

    /**
     * 小程序app_secret
     *
     * @return
     */
    String appSecret() default "";

    /**
     * @return 数据处理器  默认 DefaultWxMimiProgramHandler
     */
    Class<? extends IWxMimiProgramHandler> wxMimiProgramHandler() default DefaultWxMimiProgramHandler.class;


    /**
     * @return 默认数据处理器是否调用数据库  默认false   如调用数据库 需要sql文件执行
     */
    boolean dataHandlerDefaultByDatabases() default false;

}
