package com.dpstudio.module.doc;

import com.dpstudio.module.doc.bean.ApiResult;
import net.ymate.platform.core.IApplication;
import net.ymate.platform.core.beans.annotation.Ignored;
import net.ymate.platform.core.support.IDestroyable;
import net.ymate.platform.core.support.IInitialization;

/**
 * IDoc generated By ModuleMojo on 2020/07/07 15:44
 *
 * @author YMP (https://www.ymate.net/)
 */
@Ignored
public interface IDoc extends IInitialization<IApplication>, IDestroyable {

    String MODULE_NAME = "dpstudio.doc";

    String CHARSET = "utf-8";

    /**
     * 获取所属应用容器
     *
     * @return 返回所属应用容器实例
     */
    IApplication getOwner();

    /**
     * 获取配置
     *
     * @return 返回配置对象
     */
    IDocConfig getConfig();

    /**
     * 获取文档
     *
     * @return 文档信息
     * @throws Exception
     */
    ApiResult getDoc() throws Exception;
}
