/*
 * Copyright 2020 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dpstudio.module.wxminiprogram;


import net.ymate.platform.core.beans.annotation.Ignored;
import net.ymate.platform.core.support.IInitialization;

/**
 * ISecurityConfig generated By ModuleMojo on 2020/06/30 17:49
 *
 * @author YMP (https://www.ymate.net/)
 */
@Ignored
public interface IWxMiniProgramConfig extends IInitialization<IWxMiniProgram> {

    String ENABLED = "enabled";
    String APP_ID = "app_id";
    String APP_SECRET = "app_secret";
    String DATA_HANDLER_CLASS = "data_handler_class";
    String DATA_HANDLER_DEFAULT_BY_DATABASES = "data_handler_default_by_databases";

    /**
     * 模块是否已启用, 默认值: true
     *
     * @return 返回false表示禁用
     */
    boolean isEnabled();

    /**
     * appId
     *
     * @return appId
     */
    String appId();


    /**
     * app_secret
     *
     * @return 返回app_secret
     */
    String appSecret();


    /**
     * 数据处理器
     *
     * @return 返回数据处理器
     */
    IWxMimiProgramHandler dataHandlerClass();

    /**
     * 默认数据处理器是否调用数据库
     *
     * @return 返回默认数据处理器是否调用数据库
     */
    boolean dataHandlerDefaultByDatabases();


}