package com.dpstudio.module.security.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.IShardingable;
import net.ymate.platform.persistence.annotation.*;
import net.ymate.platform.persistence.jdbc.IConnectionHolder;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * SecurityAdminRole generated By EntityGenerator on 2020/10/19 上午 10:00:55
 *
 * @author YMP
 * @version 1.0
 */
@Entity(SecurityAdminRole.TABLE_NAME)
public class SecurityAdminRole extends BaseEntity<SecurityAdminRole, String> {

	private static final long serialVersionUID = 1L;

	@Id
	@Property(name = FIELDS.ID, nullable = false, length = 32)
	@Comment("id")
    @PropertyState(propertyName = FIELDS.ID)
	private String id;
	
	@Property(name = FIELDS.ADMIN_ID, nullable = false, length = 32)
	@Comment("管理员id")
    @PropertyState(propertyName = FIELDS.ADMIN_ID)
	private String adminId;
	
	@Property(name = FIELDS.ROLE_ID, nullable = false, length = 32)
	@Comment("角色id")
    @PropertyState(propertyName = FIELDS.ROLE_ID)
	private String roleId;
	
	@Property(name = FIELDS.CREATE_USER, nullable = false, length = 32)
	@Comment("创建人")
    @PropertyState(propertyName = FIELDS.CREATE_USER)
	private String createUser;
	
	@Property(name = FIELDS.CREATE_TIME, nullable = false, length = 13)
	@Default("0")
	@Comment("创建时间")
    @PropertyState(propertyName = FIELDS.CREATE_TIME)
	private Long createTime;
	
	@Property(name = FIELDS.LAST_MODIFY_USER, nullable = false, length = 32)
	@Comment("最后更新人")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_USER)
	private String lastModifyUser;
	
	@Property(name = FIELDS.LAST_MODIFY_TIME, nullable = false, length = 13)
	@Default("0")
	@Comment("最后更新时间")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_TIME)
	private Long lastModifyTime;

	/**
	 * 构造器
	 */
	public SecurityAdminRole() {
	}


	/**
	 * 构造器
	 *	@param id
	 *	@param adminId
	 *	@param roleId
	 *	@param createUser
	 *	@param createTime
	 *	@param lastModifyUser
	 *	@param lastModifyTime
	 */
	public SecurityAdminRole(String id, String adminId, String roleId, String createUser, Long createTime, String lastModifyUser, Long lastModifyTime) {
		this.id = id;
		this.adminId = adminId;
		this.roleId = roleId;
		this.createUser = createUser;
		this.createTime = createTime;
		this.lastModifyUser = lastModifyUser;
		this.lastModifyTime = lastModifyTime;
	}

    @Override
	public String getId() {
		return id;
	}

    @Override
	public void setId(String id) {
		this.id = id;
	}


	/**
	 * @return the adminId
	 */
	public String getAdminId() {
		return adminId;
	}

	/**
	 * @param adminId the adminId to set
	 */
	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	/**
	 * @return the roleId
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * @param roleId the roleId to set
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createTime
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the lastModifyUser
	 */
	public String getLastModifyUser() {
		return lastModifyUser;
	}

	/**
	 * @param lastModifyUser the lastModifyUser to set
	 */
	public void setLastModifyUser(String lastModifyUser) {
		this.lastModifyUser = lastModifyUser;
	}

	/**
	 * @return the lastModifyTime
	 */
	public Long getLastModifyTime() {
		return lastModifyTime;
	}

	/**
	 * @param lastModifyTime the lastModifyTime to set
	 */
	public void setLastModifyTime(Long lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}


	//
	// Chain
	//

	public static SecurityAdminRoleBuilder builder() {
		return new SecurityAdminRoleBuilder();
	}

	public SecurityAdminRoleBuilder bind() {
    	return new SecurityAdminRoleBuilder(this);
    }

	public static class SecurityAdminRoleBuilder {

		private SecurityAdminRole _model;

		public SecurityAdminRoleBuilder() {
			_model = new SecurityAdminRole();
		}

		public SecurityAdminRoleBuilder(SecurityAdminRole model) {
			_model = model;
		}

		public SecurityAdminRole build() {
			return _model;
		}


		public IConnectionHolder connectionHolder() {
			return _model.getConnectionHolder();
		}

		public SecurityAdminRoleBuilder connectionHolder(IConnectionHolder connectionHolder) {
			_model.setConnectionHolder(connectionHolder);
			return this;
		}

		public String dataSourceName() {
			return _model.getDataSourceName();
		}

		public SecurityAdminRoleBuilder dataSourceName(String dsName) {
			_model.setDataSourceName(dsName);
			return this;
		}

		public IShardingable shardingable() {
			return _model.getShardingable();
		}

		public SecurityAdminRoleBuilder shardingable(IShardingable shardingable) {
    		_model.setShardingable(shardingable);
    		return this;
    	}

		public String id() {
			return _model.getId();
		}

		public SecurityAdminRoleBuilder id(String id) {
			_model.setId(id);
			return this;
		}

		public String adminId() {
			return _model.getAdminId();
		}

		public SecurityAdminRoleBuilder adminId(String adminId) {
			_model.setAdminId(adminId);
			return this;
		}

		public String roleId() {
			return _model.getRoleId();
		}

		public SecurityAdminRoleBuilder roleId(String roleId) {
			_model.setRoleId(roleId);
			return this;
		}

		public String createUser() {
			return _model.getCreateUser();
		}

		public SecurityAdminRoleBuilder createUser(String createUser) {
			_model.setCreateUser(createUser);
			return this;
		}

		public Long createTime() {
			return _model.getCreateTime();
		}

		public SecurityAdminRoleBuilder createTime(Long createTime) {
			_model.setCreateTime(createTime);
			return this;
		}

		public String lastModifyUser() {
			return _model.getLastModifyUser();
		}

		public SecurityAdminRoleBuilder lastModifyUser(String lastModifyUser) {
			_model.setLastModifyUser(lastModifyUser);
			return this;
		}

		public Long lastModifyTime() {
			return _model.getLastModifyTime();
		}

		public SecurityAdminRoleBuilder lastModifyTime(Long lastModifyTime) {
			_model.setLastModifyTime(lastModifyTime);
			return this;
		}

	}

	/**
	 * SecurityAdminRole 字段常量表
	 */
	public class FIELDS {
		public static final String ID = "id";
		public static final String ADMIN_ID = "admin_id";
		public static final String ROLE_ID = "role_id";
		public static final String CREATE_USER = "create_user";
		public static final String CREATE_TIME = "create_time";
		public static final String LAST_MODIFY_USER = "last_modify_user";
		public static final String LAST_MODIFY_TIME = "last_modify_time";
	}

	public static final String TABLE_NAME = "security_admin_role";

}
