package com.dpstudio.module.security.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.IShardingable;
import net.ymate.platform.persistence.annotation.*;
import net.ymate.platform.persistence.jdbc.IConnectionHolder;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * SecurityRole generated By EntityGenerator on 2020/10/19 上午 10:00:55
 *
 * @author YMP
 * @version 1.0
 */
@Entity(SecurityRole.TABLE_NAME)
public class SecurityRole extends BaseEntity<SecurityRole, String> {

	private static final long serialVersionUID = 1L;

	@Id
	@Property(name = FIELDS.ID, nullable = false, length = 32)
	@Comment("id")
    @PropertyState(propertyName = FIELDS.ID)
	private String id;
	
	@Property(name = FIELDS.NAME, nullable = false, length = 100)
	@Comment("名称")
    @PropertyState(propertyName = FIELDS.NAME)
	private String name;
	
	@Property(name = FIELDS.REMARK, length = 255)
	@Comment("备注")
    @PropertyState(propertyName = FIELDS.REMARK)
	private String remark;
	
	@Property(name = FIELDS.CREATE_USER, nullable = false, length = 32)
	@Comment("创建人")
    @PropertyState(propertyName = FIELDS.CREATE_USER)
	private String createUser;
	
	@Property(name = FIELDS.CREATE_TIME, nullable = false, length = 13)
	@Default("0")
	@Comment("创建时间")
    @PropertyState(propertyName = FIELDS.CREATE_TIME)
	private Long createTime;
	
	@Property(name = FIELDS.LAST_MODIFY_USER, nullable = false, length = 32)
	@Comment("最后更新人")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_USER)
	private String lastModifyUser;
	
	@Property(name = FIELDS.LAST_MODIFY_TIME, nullable = false, length = 13)
	@Default("0")
	@Comment("最后更新时间")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_TIME)
	private Long lastModifyTime;

	/**
	 * 构造器
	 */
	public SecurityRole() {
	}

    /**
     * 构造器
     *	@param id
     *	@param name
     *	@param createUser
     *	@param createTime
     *	@param lastModifyUser
     *	@param lastModifyTime
     */
    public SecurityRole(String id, String name, String createUser, Long createTime, String lastModifyUser, Long lastModifyTime) {
        this.id = id;
        this.name = name;
        this.createUser = createUser;
        this.createTime = createTime;
        this.lastModifyUser = lastModifyUser;
        this.lastModifyTime = lastModifyTime;
    }

	/**
	 * 构造器
	 *	@param id
	 *	@param name
	 *	@param remark
	 *	@param createUser
	 *	@param createTime
	 *	@param lastModifyUser
	 *	@param lastModifyTime
	 */
	public SecurityRole(String id, String name, String remark, String createUser, Long createTime, String lastModifyUser, Long lastModifyTime) {
		this.id = id;
		this.name = name;
		this.remark = remark;
		this.createUser = createUser;
		this.createTime = createTime;
		this.lastModifyUser = lastModifyUser;
		this.lastModifyTime = lastModifyTime;
	}

    @Override
	public String getId() {
		return id;
	}

    @Override
	public void setId(String id) {
		this.id = id;
	}


	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the remark
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * @param remark the remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createTime
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the lastModifyUser
	 */
	public String getLastModifyUser() {
		return lastModifyUser;
	}

	/**
	 * @param lastModifyUser the lastModifyUser to set
	 */
	public void setLastModifyUser(String lastModifyUser) {
		this.lastModifyUser = lastModifyUser;
	}

	/**
	 * @return the lastModifyTime
	 */
	public Long getLastModifyTime() {
		return lastModifyTime;
	}

	/**
	 * @param lastModifyTime the lastModifyTime to set
	 */
	public void setLastModifyTime(Long lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}


	//
	// Chain
	//

	public static SecurityRoleBuilder builder() {
		return new SecurityRoleBuilder();
	}

	public SecurityRoleBuilder bind() {
    	return new SecurityRoleBuilder(this);
    }

	public static class SecurityRoleBuilder {

		private SecurityRole _model;

		public SecurityRoleBuilder() {
			_model = new SecurityRole();
		}

		public SecurityRoleBuilder(SecurityRole model) {
			_model = model;
		}

		public SecurityRole build() {
			return _model;
		}


		public IConnectionHolder connectionHolder() {
			return _model.getConnectionHolder();
		}

		public SecurityRoleBuilder connectionHolder(IConnectionHolder connectionHolder) {
			_model.setConnectionHolder(connectionHolder);
			return this;
		}

		public String dataSourceName() {
			return _model.getDataSourceName();
		}

		public SecurityRoleBuilder dataSourceName(String dsName) {
			_model.setDataSourceName(dsName);
			return this;
		}

		public IShardingable shardingable() {
			return _model.getShardingable();
		}

		public SecurityRoleBuilder shardingable(IShardingable shardingable) {
    		_model.setShardingable(shardingable);
    		return this;
    	}

		public String id() {
			return _model.getId();
		}

		public SecurityRoleBuilder id(String id) {
			_model.setId(id);
			return this;
		}

		public String name() {
			return _model.getName();
		}

		public SecurityRoleBuilder name(String name) {
			_model.setName(name);
			return this;
		}

		public String remark() {
			return _model.getRemark();
		}

		public SecurityRoleBuilder remark(String remark) {
			_model.setRemark(remark);
			return this;
		}

		public String createUser() {
			return _model.getCreateUser();
		}

		public SecurityRoleBuilder createUser(String createUser) {
			_model.setCreateUser(createUser);
			return this;
		}

		public Long createTime() {
			return _model.getCreateTime();
		}

		public SecurityRoleBuilder createTime(Long createTime) {
			_model.setCreateTime(createTime);
			return this;
		}

		public String lastModifyUser() {
			return _model.getLastModifyUser();
		}

		public SecurityRoleBuilder lastModifyUser(String lastModifyUser) {
			_model.setLastModifyUser(lastModifyUser);
			return this;
		}

		public Long lastModifyTime() {
			return _model.getLastModifyTime();
		}

		public SecurityRoleBuilder lastModifyTime(Long lastModifyTime) {
			_model.setLastModifyTime(lastModifyTime);
			return this;
		}

	}

	/**
	 * SecurityRole 字段常量表
	 */
	public class FIELDS {
		public static final String ID = "id";
		public static final String NAME = "name";
		public static final String REMARK = "remark";
		public static final String CREATE_USER = "create_user";
		public static final String CREATE_TIME = "create_time";
		public static final String LAST_MODIFY_USER = "last_modify_user";
		public static final String LAST_MODIFY_TIME = "last_modify_time";
	}

	public static final String TABLE_NAME = "security_role";

}
