package com.dpstudio.module.security.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.IShardingable;
import net.ymate.platform.persistence.annotation.*;
import net.ymate.platform.persistence.jdbc.IConnectionHolder;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * SecurityRolePermission generated By EntityGenerator on 2020/10/19 上午 10:00:55
 *
 * @author YMP
 * @version 1.0
 */
@Entity(SecurityRolePermission.TABLE_NAME)
public class SecurityRolePermission extends BaseEntity<SecurityRolePermission, String> {

	private static final long serialVersionUID = 1L;

	@Id
	@Property(name = FIELDS.ID, nullable = false, length = 32)
	@Comment("id")
    @PropertyState(propertyName = FIELDS.ID)
	private String id;
	
	@Property(name = FIELDS.ROLE_ID, nullable = false, length = 32)
	@Comment("角色id")
    @PropertyState(propertyName = FIELDS.ROLE_ID)
	private String roleId;
	
	@Property(name = FIELDS.GROUP_ID, nullable = false, length = 32)
	@Comment("权限组id")
    @PropertyState(propertyName = FIELDS.GROUP_ID)
	private String groupId;
	
	@Property(name = FIELDS.GROUP_NAME, nullable = false, length = 32)
	@Comment("权限组")
    @PropertyState(propertyName = FIELDS.GROUP_NAME)
	private String groupName;
	
	@Property(name = FIELDS.PERMISSION_NAME, nullable = false, length = 32)
	@Comment("权限名称")
    @PropertyState(propertyName = FIELDS.PERMISSION_NAME)
	private String permissionName;
	
	@Property(name = FIELDS.PERMISSION_CODE, nullable = false, length = 100)
	@Comment("权限码")
    @PropertyState(propertyName = FIELDS.PERMISSION_CODE)
	private String permissionCode;
	
	@Property(name = FIELDS.CREATE_USER, nullable = false, length = 32)
	@Comment("创建人")
    @PropertyState(propertyName = FIELDS.CREATE_USER)
	private String createUser;
	
	@Property(name = FIELDS.CREATE_TIME, nullable = false, length = 13)
	@Default("0")
	@Comment("创建时间")
    @PropertyState(propertyName = FIELDS.CREATE_TIME)
	private Long createTime;
	
	@Property(name = FIELDS.LAST_MODIFY_USER, nullable = false, length = 32)
	@Comment("最后更新人")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_USER)
	private String lastModifyUser;
	
	@Property(name = FIELDS.LAST_MODIFY_TIME, nullable = false, length = 13)
	@Default("0")
	@Comment("最后更新时间")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_TIME)
	private Long lastModifyTime;

	/**
	 * 构造器
	 */
	public SecurityRolePermission() {
	}


	/**
	 * 构造器
	 *	@param id
	 *	@param roleId
	 *	@param groupId
	 *	@param groupName
	 *	@param permissionName
	 *	@param permissionCode
	 *	@param createUser
	 *	@param createTime
	 *	@param lastModifyUser
	 *	@param lastModifyTime
	 */
	public SecurityRolePermission(String id, String roleId, String groupId, String groupName, String permissionName, String permissionCode, String createUser, Long createTime, String lastModifyUser, Long lastModifyTime) {
		this.id = id;
		this.roleId = roleId;
		this.groupId = groupId;
		this.groupName = groupName;
		this.permissionName = permissionName;
		this.permissionCode = permissionCode;
		this.createUser = createUser;
		this.createTime = createTime;
		this.lastModifyUser = lastModifyUser;
		this.lastModifyTime = lastModifyTime;
	}

    @Override
	public String getId() {
		return id;
	}

    @Override
	public void setId(String id) {
		this.id = id;
	}


	/**
	 * @return the roleId
	 */
	public String getRoleId() {
		return roleId;
	}

	/**
	 * @param roleId the roleId to set
	 */
	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	/**
	 * @return the groupId
	 */
	public String getGroupId() {
		return groupId;
	}

	/**
	 * @param groupId the groupId to set
	 */
	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	/**
	 * @return the groupName
	 */
	public String getGroupName() {
		return groupName;
	}

	/**
	 * @param groupName the groupName to set
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	/**
	 * @return the permissionName
	 */
	public String getPermissionName() {
		return permissionName;
	}

	/**
	 * @param permissionName the permissionName to set
	 */
	public void setPermissionName(String permissionName) {
		this.permissionName = permissionName;
	}

	/**
	 * @return the permissionCode
	 */
	public String getPermissionCode() {
		return permissionCode;
	}

	/**
	 * @param permissionCode the permissionCode to set
	 */
	public void setPermissionCode(String permissionCode) {
		this.permissionCode = permissionCode;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createTime
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the lastModifyUser
	 */
	public String getLastModifyUser() {
		return lastModifyUser;
	}

	/**
	 * @param lastModifyUser the lastModifyUser to set
	 */
	public void setLastModifyUser(String lastModifyUser) {
		this.lastModifyUser = lastModifyUser;
	}

	/**
	 * @return the lastModifyTime
	 */
	public Long getLastModifyTime() {
		return lastModifyTime;
	}

	/**
	 * @param lastModifyTime the lastModifyTime to set
	 */
	public void setLastModifyTime(Long lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}


	//
	// Chain
	//

	public static SecurityRolePermissionBuilder builder() {
		return new SecurityRolePermissionBuilder();
	}

	public SecurityRolePermissionBuilder bind() {
    	return new SecurityRolePermissionBuilder(this);
    }

	public static class SecurityRolePermissionBuilder {

		private SecurityRolePermission _model;

		public SecurityRolePermissionBuilder() {
			_model = new SecurityRolePermission();
		}

		public SecurityRolePermissionBuilder(SecurityRolePermission model) {
			_model = model;
		}

		public SecurityRolePermission build() {
			return _model;
		}


		public IConnectionHolder connectionHolder() {
			return _model.getConnectionHolder();
		}

		public SecurityRolePermissionBuilder connectionHolder(IConnectionHolder connectionHolder) {
			_model.setConnectionHolder(connectionHolder);
			return this;
		}

		public String dataSourceName() {
			return _model.getDataSourceName();
		}

		public SecurityRolePermissionBuilder dataSourceName(String dsName) {
			_model.setDataSourceName(dsName);
			return this;
		}

		public IShardingable shardingable() {
			return _model.getShardingable();
		}

		public SecurityRolePermissionBuilder shardingable(IShardingable shardingable) {
    		_model.setShardingable(shardingable);
    		return this;
    	}

		public String id() {
			return _model.getId();
		}

		public SecurityRolePermissionBuilder id(String id) {
			_model.setId(id);
			return this;
		}

		public String roleId() {
			return _model.getRoleId();
		}

		public SecurityRolePermissionBuilder roleId(String roleId) {
			_model.setRoleId(roleId);
			return this;
		}

		public String groupId() {
			return _model.getGroupId();
		}

		public SecurityRolePermissionBuilder groupId(String groupId) {
			_model.setGroupId(groupId);
			return this;
		}

		public String groupName() {
			return _model.getGroupName();
		}

		public SecurityRolePermissionBuilder groupName(String groupName) {
			_model.setGroupName(groupName);
			return this;
		}

		public String permissionName() {
			return _model.getPermissionName();
		}

		public SecurityRolePermissionBuilder permissionName(String permissionName) {
			_model.setPermissionName(permissionName);
			return this;
		}

		public String permissionCode() {
			return _model.getPermissionCode();
		}

		public SecurityRolePermissionBuilder permissionCode(String permissionCode) {
			_model.setPermissionCode(permissionCode);
			return this;
		}

		public String createUser() {
			return _model.getCreateUser();
		}

		public SecurityRolePermissionBuilder createUser(String createUser) {
			_model.setCreateUser(createUser);
			return this;
		}

		public Long createTime() {
			return _model.getCreateTime();
		}

		public SecurityRolePermissionBuilder createTime(Long createTime) {
			_model.setCreateTime(createTime);
			return this;
		}

		public String lastModifyUser() {
			return _model.getLastModifyUser();
		}

		public SecurityRolePermissionBuilder lastModifyUser(String lastModifyUser) {
			_model.setLastModifyUser(lastModifyUser);
			return this;
		}

		public Long lastModifyTime() {
			return _model.getLastModifyTime();
		}

		public SecurityRolePermissionBuilder lastModifyTime(Long lastModifyTime) {
			_model.setLastModifyTime(lastModifyTime);
			return this;
		}

	}

	/**
	 * SecurityRolePermission 字段常量表
	 */
	public class FIELDS {
		public static final String ID = "id";
		public static final String ROLE_ID = "role_id";
		public static final String GROUP_ID = "group_id";
		public static final String GROUP_NAME = "group_name";
		public static final String PERMISSION_NAME = "permission_name";
		public static final String PERMISSION_CODE = "permission_code";
		public static final String CREATE_USER = "create_user";
		public static final String CREATE_TIME = "create_time";
		public static final String LAST_MODIFY_USER = "last_modify_user";
		public static final String LAST_MODIFY_TIME = "last_modify_time";
	}

	public static final String TABLE_NAME = "security_role_permission";

}
