package com.dpstudio.module.security.model;

import net.ymate.platform.core.beans.annotation.PropertyState;
import net.ymate.platform.persistence.IShardingable;
import net.ymate.platform.persistence.annotation.*;
import net.ymate.platform.persistence.jdbc.IConnectionHolder;
import net.ymate.platform.persistence.jdbc.support.BaseEntity;

/**
 * SecurityAdminLog generated By EntityGenerator on 2020/10/19 上午 10:00:54
 *
 * @author YMP
 * @version 1.0
 */
@Entity(SecurityAdminLog.TABLE_NAME)
public class SecurityAdminLog extends BaseEntity<SecurityAdminLog, String> {

	private static final long serialVersionUID = 1L;

	@Id
	@Property(name = FIELDS.ID, nullable = false, length = 32)
	@Comment("")
    @PropertyState(propertyName = FIELDS.ID)
	private String id;
	
	@Property(name = FIELDS.TYPE, nullable = false, length = 2)
	@Comment("类型")
    @PropertyState(propertyName = FIELDS.TYPE)
	private Integer type;
	
	@Property(name = FIELDS.ACTION, nullable = false, length = 100)
	@Comment("动作")
    @PropertyState(propertyName = FIELDS.ACTION)
	private String action;
	
	@Property(name = FIELDS.ADMIN_ID, length = 32)
	@Comment("管理员id")
    @PropertyState(propertyName = FIELDS.ADMIN_ID)
	private String adminId;
	
	@Property(name = FIELDS.CONTENT, nullable = false, length = 16383)
	@Comment("内容")
    @PropertyState(propertyName = FIELDS.CONTENT)
	private String content;
	
	@Property(name = FIELDS.CREATE_USER, nullable = false, length = 32)
	@Comment("创建人")
    @PropertyState(propertyName = FIELDS.CREATE_USER)
	private String createUser;
	
	@Property(name = FIELDS.CREATE_TIME, nullable = false, length = 13)
	@Default("0")
	@Comment("创建时间")
    @PropertyState(propertyName = FIELDS.CREATE_TIME)
	private Long createTime;
	
	@Property(name = FIELDS.LAST_MODIFY_USER, nullable = false, length = 32)
	@Comment("最后修改人")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_USER)
	private String lastModifyUser;
	
	@Property(name = FIELDS.LAST_MODIFY_TIME, nullable = false, length = 13)
	@Default("0")
	@Comment("最后修改时间")
    @PropertyState(propertyName = FIELDS.LAST_MODIFY_TIME)
	private Long lastModifyTime;

	/**
	 * 构造器
	 */
	public SecurityAdminLog() {
	}

    /**
     * 构造器
     *	@param id
     *	@param type
     *	@param action
     *	@param content
     *	@param createUser
     *	@param createTime
     *	@param lastModifyUser
     *	@param lastModifyTime
     */
    public SecurityAdminLog(String id, Integer type, String action, String content, String createUser, Long createTime, String lastModifyUser, Long lastModifyTime) {
        this.id = id;
        this.type = type;
        this.action = action;
        this.content = content;
        this.createUser = createUser;
        this.createTime = createTime;
        this.lastModifyUser = lastModifyUser;
        this.lastModifyTime = lastModifyTime;
    }

	/**
	 * 构造器
	 *	@param id
	 *	@param type
	 *	@param action
	 *	@param adminId
	 *	@param content
	 *	@param createUser
	 *	@param createTime
	 *	@param lastModifyUser
	 *	@param lastModifyTime
	 */
	public SecurityAdminLog(String id, Integer type, String action, String adminId, String content, String createUser, Long createTime, String lastModifyUser, Long lastModifyTime) {
		this.id = id;
		this.type = type;
		this.action = action;
		this.adminId = adminId;
		this.content = content;
		this.createUser = createUser;
		this.createTime = createTime;
		this.lastModifyUser = lastModifyUser;
		this.lastModifyTime = lastModifyTime;
	}

    @Override
	public String getId() {
		return id;
	}

    @Override
	public void setId(String id) {
		this.id = id;
	}


	/**
	 * @return the type
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * @param type the type to set
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * @return the action
	 */
	public String getAction() {
		return action;
	}

	/**
	 * @param action the action to set
	 */
	public void setAction(String action) {
		this.action = action;
	}

	/**
	 * @return the adminId
	 */
	public String getAdminId() {
		return adminId;
	}

	/**
	 * @param adminId the adminId to set
	 */
	public void setAdminId(String adminId) {
		this.adminId = adminId;
	}

	/**
	 * @return the content
	 */
	public String getContent() {
		return content;
	}

	/**
	 * @param content the content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * @return the createUser
	 */
	public String getCreateUser() {
		return createUser;
	}

	/**
	 * @param createUser the createUser to set
	 */
	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	/**
	 * @return the createTime
	 */
	public Long getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime the createTime to set
	 */
	public void setCreateTime(Long createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the lastModifyUser
	 */
	public String getLastModifyUser() {
		return lastModifyUser;
	}

	/**
	 * @param lastModifyUser the lastModifyUser to set
	 */
	public void setLastModifyUser(String lastModifyUser) {
		this.lastModifyUser = lastModifyUser;
	}

	/**
	 * @return the lastModifyTime
	 */
	public Long getLastModifyTime() {
		return lastModifyTime;
	}

	/**
	 * @param lastModifyTime the lastModifyTime to set
	 */
	public void setLastModifyTime(Long lastModifyTime) {
		this.lastModifyTime = lastModifyTime;
	}


	//
	// Chain
	//

	public static SecurityAdminLogBuilder builder() {
		return new SecurityAdminLogBuilder();
	}

	public SecurityAdminLogBuilder bind() {
    	return new SecurityAdminLogBuilder(this);
    }

	public static class SecurityAdminLogBuilder {

		private SecurityAdminLog _model;

		public SecurityAdminLogBuilder() {
			_model = new SecurityAdminLog();
		}

		public SecurityAdminLogBuilder(SecurityAdminLog model) {
			_model = model;
		}

		public SecurityAdminLog build() {
			return _model;
		}


		public IConnectionHolder connectionHolder() {
			return _model.getConnectionHolder();
		}

		public SecurityAdminLogBuilder connectionHolder(IConnectionHolder connectionHolder) {
			_model.setConnectionHolder(connectionHolder);
			return this;
		}

		public String dataSourceName() {
			return _model.getDataSourceName();
		}

		public SecurityAdminLogBuilder dataSourceName(String dsName) {
			_model.setDataSourceName(dsName);
			return this;
		}

		public IShardingable shardingable() {
			return _model.getShardingable();
		}

		public SecurityAdminLogBuilder shardingable(IShardingable shardingable) {
    		_model.setShardingable(shardingable);
    		return this;
    	}

		public String id() {
			return _model.getId();
		}

		public SecurityAdminLogBuilder id(String id) {
			_model.setId(id);
			return this;
		}

		public Integer type() {
			return _model.getType();
		}

		public SecurityAdminLogBuilder type(Integer type) {
			_model.setType(type);
			return this;
		}

		public String action() {
			return _model.getAction();
		}

		public SecurityAdminLogBuilder action(String action) {
			_model.setAction(action);
			return this;
		}

		public String adminId() {
			return _model.getAdminId();
		}

		public SecurityAdminLogBuilder adminId(String adminId) {
			_model.setAdminId(adminId);
			return this;
		}

		public String content() {
			return _model.getContent();
		}

		public SecurityAdminLogBuilder content(String content) {
			_model.setContent(content);
			return this;
		}

		public String createUser() {
			return _model.getCreateUser();
		}

		public SecurityAdminLogBuilder createUser(String createUser) {
			_model.setCreateUser(createUser);
			return this;
		}

		public Long createTime() {
			return _model.getCreateTime();
		}

		public SecurityAdminLogBuilder createTime(Long createTime) {
			_model.setCreateTime(createTime);
			return this;
		}

		public String lastModifyUser() {
			return _model.getLastModifyUser();
		}

		public SecurityAdminLogBuilder lastModifyUser(String lastModifyUser) {
			_model.setLastModifyUser(lastModifyUser);
			return this;
		}

		public Long lastModifyTime() {
			return _model.getLastModifyTime();
		}

		public SecurityAdminLogBuilder lastModifyTime(Long lastModifyTime) {
			_model.setLastModifyTime(lastModifyTime);
			return this;
		}

	}

	/**
	 * SecurityAdminLog 字段常量表
	 */
	public class FIELDS {
		public static final String ID = "id";
		public static final String TYPE = "type";
		public static final String ACTION = "action";
		public static final String ADMIN_ID = "admin_id";
		public static final String CONTENT = "content";
		public static final String CREATE_USER = "create_user";
		public static final String CREATE_TIME = "create_time";
		public static final String LAST_MODIFY_USER = "last_modify_user";
		public static final String LAST_MODIFY_TIME = "last_modify_time";
	}

	public static final String TABLE_NAME = "security_admin_log";

}
