/*
 * Copyright 2021 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dpstudio.module.mybatis;

import net.ymate.platform.core.beans.annotation.Ignored;
import net.ymate.platform.core.support.IInitialization;
import org.apache.ibatis.cache.Cache;
import org.apache.ibatis.io.VFS;
import org.apache.ibatis.mapping.DatabaseIdProvider;
import org.apache.ibatis.plugin.Interceptor;
import org.apache.ibatis.reflection.factory.ObjectFactory;
import org.apache.ibatis.reflection.wrapper.ObjectWrapperFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;
import org.apache.ibatis.transaction.TransactionFactory;
import org.apache.ibatis.type.TypeHandler;

import java.util.List;

/**
 * IMybatisConfig generated By ModuleMojo on 2021/02/22 16:46
 *
 * @author YMP (https://www.ymate.net/)
 */
@Ignored
public interface IMybatisConfig extends IInitialization<IMybatis> {

    String CONFIG_LOCATION = "configLocation";
    String MAPPER_LOCATIONS = "mapperLocations";
    String TRANSACTION_FACTORY = "transactionFactory";
    String CONFIGURATION_PROPERTIES = "configurationProperties";
    String ENVIRONMENT = "environment";
    String PLUGINS = "plugins";
    String TYPE_HANDLERS = "typeHandlers";
    String TYPE_HANDLERS_PACKAGE = "typeHandlersPackage";
    String TYPE_ALIASES = "typeAliases";
    String TYPE_ALIASES_PACKAGE = "typeAliasesPackage";
    String TYPE_ALIASES_SUPERTYPE = "typeAliasesSuperType";
    String DATABASE_ID_PROVIDER = "databaseIdProvider";
    String VFS_STR = "vfs";
    String CACHE = "cache";
    String OBJECT_FACTORY = "objectFactory";
    String OBJECT_WRAPPER_FACTORY = "objectWrapperFactory";

    String configLocation();

    String mapperLocations();

    TransactionFactory transactionFactory();

    String configurationProperties();

    String environment();

    List<Interceptor> plugins();

    List<TypeHandler> typeHandlers();

    List<String> typeHandlersPackage();

    List<Class<?>> typeAliases();

    List<String> typeAliasesPackage();

    Class<?> typeAliasesSuperType();

    DatabaseIdProvider databaseIdProvider();

    Class<? extends VFS> vfs();

    Cache cache();

    ObjectFactory objectFactory();

    ObjectWrapperFactory objectWrapperFactory();
}