/*
 * Copyright 2021 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.dpstudio.module.mybatis;

import com.dpstudio.module.mybatis.impl.DefaultMybatisConfig;
import net.ymate.platform.core.*;
import net.ymate.platform.core.module.IModule;
import net.ymate.platform.core.module.IModuleConfigurer;
import net.ymate.platform.core.module.impl.DefaultModuleConfigurer;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionManager;

/**
 * Mybatis generated By ModuleMojo on 2021/02/22 16:46
 *
 * @author YMP (https://www.ymate.net/)
 */
public final class Mybatis implements IModule, IMybatis {

    private static final Log LOG = LogFactory.getLog(Mybatis.class);

    private static volatile IMybatis instance;

    private IApplication owner;

    private IMybatisConfig config;

    private boolean initialized;

    private static SqlSessionFactory sqlSessionFactory;

    public static IMybatis get() {
        IMybatis inst = instance;
        if (inst == null) {
            synchronized (Mybatis.class) {
                inst = instance;
                if (inst == null) {
                    instance = inst = YMP.get().getModuleManager().getModule(Mybatis.class);
                }
            }
        }
        return inst;
    }

    public Mybatis() {
    }

    public Mybatis(IMybatisConfig config) {
        this.config = config;
    }

    @Override
    public String getName() {
        return MODULE_NAME;
    }

    @Override
    public void initialize(IApplication owner) throws Exception {
        if (!initialized) {
            //
            System.out.println("mybatis");
            YMP.showVersion("Initializing dpstudio-module-mybatis-mybatis-${version}", new Version(1, 0, 0, Mybatis.class, Version.VersionType.Alpha));
            //
            this.owner = owner;
            if (config == null) {
                IApplicationConfigureFactory configureFactory = owner.getConfigureFactory();
                if (configureFactory != null) {
                    IApplicationConfigurer configurer = configureFactory.getConfigurer();
                    IModuleConfigurer moduleConfigurer = configurer == null ? null : configurer.getModuleConfigurer(MODULE_NAME);
                    if (moduleConfigurer != null) {
                        config = DefaultMybatisConfig.create(configureFactory.getMainClass(), moduleConfigurer);
                    } else {
                        config = DefaultMybatisConfig.create(configureFactory.getMainClass(), DefaultModuleConfigurer.createEmpty(MODULE_NAME));
                    }
                }
                if (config == null) {
                    config = DefaultMybatisConfig.defaultConfig();
                }
            }
            if (!config.isInitialized()) {
                config.initialize(this);
            }
            if (sqlSessionFactory == null) {
                sqlSessionFactory = SqlSessionFactoryHelper.initialize(config);
            }
            initialized = true;
        }
    }

    @Override
    public boolean isInitialized() {
        return initialized;
    }

    @Override
    public void close() throws Exception {
        if (initialized) {
            initialized = false;
            sqlSessionFactory = null;
            config = null;
            owner = null;
        }
    }

    @Override
    public IApplication getOwner() {
        return owner;
    }

    @Override
    public IMybatisConfig getConfig() {
        return config;
    }

    @Override
    public SqlSessionFactory sqlsessionfactory() {
        return sqlSessionFactory;
    }

    @Override
    public SqlSessionManager sqlSessionManager() {
        return SqlSessionManager.newInstance(sqlSessionFactory);
    }
}
