/*
 * Copyright 2021 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.mx.module.mybatis;

import net.ymate.platform.core.IApplication;
import net.ymate.platform.core.beans.annotation.Ignored;
import net.ymate.platform.core.support.IDestroyable;
import net.ymate.platform.core.support.IInitialization;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionManager;

/**
 * IMybatis generated By ModuleMojo on 2021/02/22 16:46
 *
 * @author YMP (https://www.ymate.net/)
 */
@Ignored
public interface IMybatis extends IInitialization<IApplication>, IDestroyable {

    String MODULE_NAME = "module.mybatis";

    /**
     * 获取所属应用容器
     *
     * @return 返回所属应用容器实例
     */
    IApplication getOwner();

    /**
     * 获取配置
     *
     * @return 返回配置对象
     */
    IMybatisConfig getConfig();

    /**
     * 获取SqlSessionFactory对象
     * @return
     */
    SqlSessionFactory sqlsessionfactory();

    /**
     * 获取SqlSessionManager对象
     * @return
     */
    SqlSessionManager sqlSessionManager();
}
